// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqmuzemeyndcpovfbjqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxbXV6ZW1leW5kY3BvdmZianF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MDMzMzcsImV4cCI6MjA1OTM3OTMzN30.ndDckcXcO4IHXVkeCSldKgw2H0um8zqDztFzkKs22bs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);